#11 added error checks and with credentials blocks

diff --git a/ci/jobs/writio-release-branch/Jenkinsfile b/ci/jobs/writio-release-branch/Jenkinsfile
--- a/ci/jobs/writio-release-branch/Jenkinsfile
+++ b/ci/jobs/writio-release-branch/Jenkinsfile
@@ -3,8 +3,8 @@ def defaultBranch = 'dev'
 
 pipeline {
     parameters {
-        gitParameter(branchFilter: 'origin/(.*)', defaultValue: defaultBranch, name: 'branch', type: 'PT_BRANCH', description: "writio branch to release from")
-        string(name: "version", defaultValue: "<version>", description: "writio release version")
+        gitParameter(name: 'branch', branchFilter: 'origin/(.*)', defaultValue: defaultBranch, type: 'PT_BRANCH', description: "writio branch to release from")
+        string(name: "version", defaultValue: "", description: "writio release version")
         string(name: "name", defaultValue: "", description: "Firstname Lastname")
         string(name: "email", defaultValue: "", description: "Your email address")
         credentials(name: 'credentials', credentialType: 'com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl', description: 'writio GitHub credentials', required: true)
@@ -18,10 +18,16 @@ pipeline {
         stage('parameterization') {
             steps {
                 script {
+				
                     if ("${params.parameterization}" == 'true') {
                         currentBuild.result = 'aborted'
                         error('dry run completed, job parameterized')
                     }
+					
+					if (!(params.branch?.trim())) { error("Build failed because source branch is not selected!")}
+					if (!(params.version?.trim())) { error("Build failed because no release version was provided!")}
+					if (!(params.name?.trim())) { error("Build failed because no name was provided!")}
+					if (!(params.email?.trim())) { error("Build failed because no email was provided!")}
                 }
             }
         }
@@ -36,19 +42,18 @@ pipeline {
                     sh "git config --global user.name \"${params.name}\""
                     sh "git config --global user.email ${params.email}"
 					
-					sh "git config --global credential.helper cache"
-					sh "git config --global push.default simple"
-					
-					/*withCredentials([usernamePassword(credentialsId: "${params.credentials}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
+					withCredentials([usernamePassword(credentialsId: "${params.credentials}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
 						repositoryUrl = "https://${USERNAME}:${PASSWORD}@github.com/cbehrenberg/writio.git"
-					}*/
+					}
 				}
             }
         }
         stage('clone source branch') {
             steps {
-                echo "cloning git branch '${params.branch}'..."
-                git branch: "${params.branch}", credentialsId: "${params.credentials}", changelog: false, poll: false, url: repositoryUrl
+				withCredentials([usernamePassword(credentialsId: "${params.credentials}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
+					echo "cloning git branch '${params.branch}'..."
+					git branch: "${params.branch}", credentialsId: "${params.credentials}", changelog: false, poll: false, url: repositoryUrl
+				}
             }
         }
         stage('build source branch') {
@@ -65,24 +70,28 @@ pipeline {
             }
             steps {
                 script {
-                    target_branch="release/${params.version}"
-                    message="create release branch for version ${params.version}"
-
-                    echo "switching to branch ${target_branch} for release..."
-                    sh "git checkout -b ${target_branch} ${params.branch}"
+					withCredentials([usernamePassword(credentialsId: "${params.credentials}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                     
-                    echo "switching maven version ${params.version}..."
-                    sh "mvn versions:set -DnewVersion=${params.version} -DgenerateBackupPoms=false"
-                    
-                    echo "switching latest to specific version ${version} for container yamls..."
-                    sh "sed -i \"s/latest/${params.version}/g\" ./ci/.env"
-                    sh "cat ./ci/.env"
+						target_branch="release/${params.version}"
+						message="create release branch for version ${params.version}"
 
-                    echo "comitting changes locally..."
-                    sh "git commit -a -m \"${message}\""
-					
-					echo "pushing changes to remote..."
-					sh "git push origin \"${target_branch}\""
+						echo "switching to branch ${target_branch} for release..."
+						sh "git checkout -b ${target_branch} ${params.branch}"
+						
+						echo "switching maven version ${params.version}..."
+						sh "mvn versions:set -DnewVersion=${params.version} -DgenerateBackupPoms=false"
+						
+						echo "switching latest to specific version ${version} for container yamls..."
+						sh "sed -i \"s/latest/${params.version}/g\" ./ci/.env"
+						sh "cat ./ci/.env"
+
+						echo "comitting changes locally..."
+						sh "git commit -a -m \"${message}\""
+						
+						echo "pushing changes to remote..."
+						
+						sh "git push origin \"${target_branch}\""
+					}
                 }
             }
         }
